DELIMITER //

DROP PROCEDURE IF EXISTS GETAMOUNT//
CREATE PROCEDURE GETAMOUNT (OUT val LONG, IN idx INT)
  BEGIN
    SELECT `value` INTO val FROM `users` WHERE `user_id` = idx;
  END//

DROP PROCEDURE IF EXISTS ADDAMOUNT//
CREATE PROCEDURE ADDAMOUNT(IN idx INT,IN val LONG)
  BEGIN
    INSERT INTO `users`(`user_id`,`value`) VALUES(idx,val);
  END //

DELIMITER ;
